version: '3.8'
#servicesとは、コンテナの定義を記述する
services:
  postgres:
  #imageとは、コンテナのイメージを指定する
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=eringiv3
      - POSTGRES_PASSWORD=password
      #volumeとは、コンテナのデータをホストのディレクトリにマウントする
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:

  #コメントアウト